head: 
   favicon: "/favicon.ico" #  the favicon
   high_res_favicon: "/favicon.ico" #  the favicon using high quality format
   apple_touch_icon: "/favicon.ico" # the iOS Home button icon
   keywords: "blog jekyll 耀日庄主 SunbossRS 博客" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background: 
   purecolor: "img('/assets/images/logo-chhandwrite.jpg')" # the background color

img: 
   avatar: "/assets/images/avatar.jpg" # your avatar

card: 
   card_shadow: 9 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: true
   weibo: true
   linkedin: false
   qq: true
   telegram: false
  
comment:
  used: "gitalk" # gitalk
  # GitalkSettings
  gitalk: true
  gitalk_clientid: '800a929ad18c8e90fdbc'
  gitalk_secret: '3dcb1cc3680b9b85ad4291367b4aafefd6806e58'
  gitalk_repo: 'SunTalk_Save'
  gitalk_owner: 'SunbossRS'
  gitalk_admin: 'SunbossRS'
  dfm: true

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: ""  # google analytics code

baidu_site_verification: ""  # baidu site verification code
google_site_verification: ""  # google search console verification code

baidu_auto_push: false  # if you used baidu auto push to commit links

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
